# Generated by Django 3.2.8 on 2021-11-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_alt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
