# Generated by Django 3.2.8 on 2021-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visit_website',
            field=models.URLField(null=True),
        ),
    ]
