# Generated by Django 3.2.8 on 2021-11-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_project_visit_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='visit_website',
            new_name='repo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.URLField(null=True),
        ),
    ]
